export const ADD_NOTE = "ADD_NOTE";
export const TOGGLE_NEW_NOTE_FORM = "TOGGLE_NEW_NOTE_FORM";
export const ADD_JOURNAL = "ADD_JOURNAL";
export const CHANGE_JOURNAL = "CHANGE_CURRENTLY_SELECTED_JOURNAL";
export const TOGGLE_NEW_JOURNAL_MODAL = "TOGGLE_NEW_JOURNAL_MODAL";
export const GOOGLE_SIGN_IN_SUCCESS = "GOOGLE_SIGN_IN_SUCCESS";
export const GOOGLE_SIGN_OUT_SUCCESS = "GOOGLE_SIGN_OUT_SUCCESS";
export const AUTHENTICATION_STATUS_CHANGE_IS_COMPLETE =
  "AUTHENTICATION_STATUS_CHANGE_IS_COMPLETE";
export const ADD_CURRENT_USER = "ADD_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const REQUEST_JOURNALS = "REQUEST_JOURNALS";
export const GET_JOURNALS_SUCCESS = "GET_JOURNALS_SUCCESS";
export const GET_JOURNALS_FAILURE = "GET_JOURNALS_FAILURE";
export const REQUEST_NOTES = "REQUEST_NOTES";
export const GET_NOTES_SUCCESS = "GET_NOTES_SUCCESS";
export const GET_NOTES_FAILURE = "GET_NOTES_FAILURE";
