export const ADD_NOTE = "ADD_NOTE";
export const TOGGLE_NEW_NOTE_FORM = "TOGGLE_NEW_NOTE_FORM";
export const ADD_JOURNAL = "ADD_JOURNAL";
export const CHANGE_JOURNAL = "CHANGE_CURRENTLY_SELECTED_JOURNAL";
export const TOGGLE_NEW_JOURNAL_MODAL = "TOGGLE_NEW_JOURNAL_MODAL";
